1.0.3.1

diff --git a/jobs/redis_check/templates/bin/run.erb b/jobs/redis_check/templates/bin/run.erb
--- a/jobs/redis_check/templates/bin/run.erb
+++ b/jobs/redis_check/templates/bin/run.erb
@@ -50,6 +50,7 @@ then
   fi
 fi
 <%- end -%>
+CLI_CLUSTER_OPTS="";
 
 #
 # Look up Redis instances
@@ -67,15 +68,15 @@ else
   echo "ERROR: Redis server at address [${REDIS_IP}] and port [${REDIS_PORT}] is unavailable: \"${MSG}\"." >&2;
 fi
 
-#
-# Look up Redis Sentinel instances
-#
 <%- if master.p('replication') && !sentinel.nil?
   sentinel_addresses=''
   sentinel.instances.each{ |x| sentinel_addresses.concat(x.address).concat(' ') }
   if !sentinel_slave.nil?
     sentinel_slave.instances.each{ |x| sentinel_addresses.concat(x.address).concat(' ') }
   end -%>
+#
+# Look up Redis Sentinel instances
+#
 SENTINEL_ADDRESSES="<%= sentinel_addresses %>";
 SENTINEL_PORT="<%= sentinel.p('port') %>";
 SENTINEL_CRED="";
@@ -142,13 +143,12 @@ do
     echo "ERROR: Redis Sentinel at address [${x}] and port [${SENTINEL_PORT}] is unavailable: \"${MSG}\"." >&2;
   fi
 done
-<%- end -%>
-
-#
-# Look up Redis cluster
-#
-CLI_CLUSTER_OPTS="";
-<%- if master.p('cluster_enabled').eql?('yes')
+<%- end
+  if master.p('cluster_enabled').eql?('yes')
+  node_port=master.p('port')
+  if master.p('tls') && master.p('tls_cluster')
+    node_port=master.p('tls_port')
+  end
   master_addresses=''
   master.instances.each{ |x| master_addresses.concat(x.address).concat(' ') }
   master_instances=master.instances.length
@@ -176,6 +176,9 @@ CLI_CLUSTER_OPTS="";
       replicas_per_node=0
     end
   end -%>
+#
+# Look up Redis cluster
+#
 MASTER_ADDRESSES="<%= master_addresses %>";
 MASTER_INSTANCES="<%= master_instances %>";
 SLAVE_ADDRESSES="<%= slaves_addresses %>";
@@ -183,12 +186,14 @@ SLAVE_INSTANCES="<%= slave_instances %>";
 REDIS_ADDRESSES="${MASTER_ADDRESSES} ${SLAVE_ADDRESSES}";
 REDIS_INSTANCES="<%= master_instances+slave_instances %>";
 REPLICAS_PER_NODE="<%= replicas_per_node %>";
+NODE_PORT="<%= node_port %>";
 
 echo "#### Initial masters addresses: [${MASTER_ADDRESSES}]";
 echo "#### Number of masters: [${MASTER_INSTANCES}]";
 echo "#### Initial slaves addresses: [${SLAVE_ADDRESSES}]";
 echo "#### Number of slaves: [${SLAVE_INSTANCES}]";
 echo "#### Replicas per master: [${REPLICAS_PER_NODE}]";
+echo "#### Nodes port: [${NODE_PORT}]";
 
 MSG="$("${CLI}" \
   -h "${REDIS_IP}" \
@@ -198,14 +203,13 @@ MSG="$("${CLI}" \
 ERR=${?};
 if [[ ${ERR} -eq 0 ]];
 then
-  echo "Redis CLUSTER NODES command results:";
-  echo "${MSG}";
+  echo "#### Redis CLUSTER NODES command results: \"${MSG}\"".
   AVAILABLE_NODES=0;
   for i in $(echo "${MSG}" | awk '{print $2;}');
   do
     for j in ${REDIS_ADDRESSES};
     do
-      if [[ "${i%%@*}" == "${j}:${REDIS_PORT}" ]];
+      if [[ "${i%%@*}" == "${j}:${NODE_PORT}" ]];
       then
         ((AVAILABLE_NODES++));
       fi
@@ -219,20 +223,20 @@ then
     then
       echo "#### All required Redis master nodes [${MASTER_INSTANCES}] are available.";
     else
-      echo "ERROR: The required Redis master nodes [${MASTER_INSTANCES}] is not equal to the available master nodes [${AVAILABLE_NODES}]." >&2;
       ERR=1;
+      echo "ERROR: The required Redis master nodes [${MASTER_INSTANCES}] is not equal to the available master nodes [${AVAILABLE_NODES}]." >&2;
     fi
     AVAILABLE_NODES=$(echo "${MSG}" | awk '$3~/slave/{print $2;}' | wc -l);
     if [[ ${SLAVE_INSTANCES} -eq ${AVAILABLE_NODES} ]];
     then
       echo "#### All required Redis slave nodes [${SLAVE_INSTANCES}] are available";
     else
-      echo "ERROR: The required Redis slave nodes [${SLAVE_INSTANCES}] is not equal to the available slave nodes [${AVAILABLE_NODES}]." >&2;
       ERR=1;
+      echo "ERROR: The required Redis slave nodes [${SLAVE_INSTANCES}] is not equal to the available slave nodes [${AVAILABLE_NODES}]." >&2;
     fi
   else
-    echo "ERROR: The required Redis nodes [${REDIS_INSTANCES}] is not equal to the available nodes [${AVAILABLE_NODES}]." >&2;
     ERR=1;
+    echo "ERROR: The required Redis nodes [${REDIS_INSTANCES}] is not equal to the available nodes [${AVAILABLE_NODES}]." >&2;
   fi
 else
   echo "ERROR: Redis CLUSTER NODES command failed: \"${MSG}\"." >&2;
@@ -264,7 +268,7 @@ then
       REDIS_PORT="${MSG#*[[:space:]]}";
       echo -e "####\n#### CRUD operations to Redis master [${REDIS_IP}:${REDIS_PORT}] get from Sentinel [${x}] :";
 <%- end -%>
-      CLI_OPTS="-h ${REDIS_IP} -p ${REDIS_PORT} ${REDIS_CRED} ${CLI_CLUSTER_OPTS}";
+      CLI_OPTS="${REDIS_CRED} ${CLI_CLUSTER_OPTS} -h ${REDIS_IP} -p ${REDIS_PORT}";
       MSG="$(${CLI} ${CLI_OPTS} SET ${KV} ${KV})";
       if [[ ${?} -eq 0 ]];
       then
