1.0.2.2

diff --git a/jobs/redis_check/templates/bin/run.erb b/jobs/redis_check/templates/bin/run.erb
--- a/jobs/redis_check/templates/bin/run.erb
+++ b/jobs/redis_check/templates/bin/run.erb
@@ -15,11 +15,12 @@ REDIS_IP="<%= spec.ip %>";
 <%- end -%>
 REDIS_PORT="<%= master.p('port') %>";
 REDIS_CRED="";
-<%- master.if_p('password') do |password|
-    unless password.to_s.empty? -%>
-REDIS_CRED="-a <%= password %>";
+<%- master.if_p('password') do |x|
+    unless x.to_s.empty? -%>
+REDIS_CRED="-a <%= x %>";
 <%- end
   end -%>
+CLI_CLUSTER_OPTS="";
 
 #
 # Look up Redis instance
@@ -37,21 +38,21 @@ else
   echo "ERROR: Redis server at address [${REDIS_IP}] and port [${REDIS_PORT}] is unavailable: \"${MSG}\"." >&2;
 fi
 
-#
-# Look up Redis Sentinel instance
-#
 <%- if master.p('replication') && !sentinel.nil?
   sentinel_addresses=''
   sentinel.instances.each{ |x| sentinel_addresses.concat(x.address).concat(' ') }
   if !sentinel_slave.nil?
     sentinel_slave.instances.each{ |x| sentinel_addresses.concat(x.address).concat(' ') }
   end -%>
+#
+# Look up Redis Sentinel instance
+#
 SENTINEL_ADDRESSES="<%= sentinel_addresses %>";
 SENTINEL_PORT="<%= sentinel.p('port') %>";
 SENTINEL_CRED="";
-<%- sentinel.if_p('password') do |password|
-    unless password.to_s.empty? -%>
-SENTINEL_CRED="-a <%= password %>";
+<%- sentinel.if_p('password') do |x|
+    unless x.to_s.empty? -%>
+SENTINEL_CRED="-a <%= x %>";
 <%- end
   end -%>
 
@@ -106,13 +107,8 @@ do
     echo "ERROR: Redis Sentinel at address [${x}] and port [${SENTINEL_PORT}] is unavailable: \"${MSG}\"." >&2;
   fi
 done
-<%- end -%>
-
-#
-# Look up Redis cluster
-#
-CLI_CLUSTER_OPTS="";
-<%- if master.p('cluster_enabled').eql?('yes')
+<%- end
+  if master.p('cluster_enabled').eql?('yes')
   master_addresses=''
   master.instances.each{ |x| master_addresses.concat(x.address).concat(' ') }
   master_instances=master.instances.length
@@ -140,6 +136,9 @@ CLI_CLUSTER_OPTS="";
       replicas_per_node=0
     end
   end -%>
+#
+# Look up Redis cluster
+#
 MASTER_ADDRESSES="<%= master_addresses %>";
 MASTER_INSTANCES="<%= master_instances %>";
 SLAVE_ADDRESSES="<%= slaves_addresses %>";
@@ -182,20 +181,20 @@ then
     then
       echo "#### All required Redis master nodes [${MASTER_INSTANCES}] are available.";
     else
-      echo "ERROR: The required Redis master nodes [${MASTER_INSTANCES}] is not equal to the available master nodes [${AVAILABLE_NODES}]." >&2;
       ERR=1;
+      echo "ERROR: The required Redis master nodes [${MASTER_INSTANCES}] is not equal to the available master nodes [${AVAILABLE_NODES}]." >&2;
     fi
     AVAILABLE_NODES=$(echo "${MSG}" | awk '$3~/slave/{print $2;}' | wc -l);
     if [[ ${SLAVE_INSTANCES} -eq ${AVAILABLE_NODES} ]];
     then
       echo "#### All required Redis slave nodes [${SLAVE_INSTANCES}] are available.";
     else
-      echo "ERROR: The required Redis slave nodes [${SLAVE_INSTANCES}] is not equal to the available slave nodes [${AVAILABLE_NODES}]." >&2;
       ERR=1;
+      echo "ERROR: The required Redis slave nodes [${SLAVE_INSTANCES}] is not equal to the available slave nodes [${AVAILABLE_NODES}]." >&2;
     fi
   else
-    echo "ERROR: The required Redis nodes [${REDIS_INSTANCES}] is not equal to the available nodes [${AVAILABLE_NODES}]." >&2;
     ERR=1;
+    echo "ERROR: The required Redis nodes [${REDIS_INSTANCES}] is not equal to the available nodes [${AVAILABLE_NODES}]." >&2;
   fi
 else
   echo "ERROR: Redis CLUSTER NODES command failed: \"${MSG}\"." >&2;
