1.0.3.1

diff --git a/jobs/redis_broker_check-1.5/templates/bin/run.erb b/jobs/redis_broker_check-1.5/templates/bin/run.erb
--- a/jobs/redis_broker_check-1.5/templates/bin/run.erb
+++ b/jobs/redis_broker_check-1.5/templates/bin/run.erb
@@ -12,40 +12,33 @@ PORT="<%= broker.p('tls_port') %>";
 PROTOCOLE="http";
 PORT="<%= broker.p('port') %>";
 <%- end -%>
-
 BASE_URI="${PROTOCOLE}://<%= broker.p('user') %>:<%= broker.p('password') %>@${IP}:${PORT}";
 
-ERR_CATALOG=1;
 if [[ "$(curl -k -s -o /dev/null -I -w "%{http_code}" \
   ${BASE_URI}/v2/catalog)" == "200" ]];
 then
-  ERR_CATALOG=0;
+  echo "#### Catalog request result:";
   echo "$(curl -k -s ${BASE_URI}/v2/catalog)";
-  echo "Catalog: OK";
+  echo "#### Catalog: OK";
 else
-  echo "Catalog: KO";
+  ERR=1;
+  echo "ERROR: Catalog: KO" >&2;
 fi
 
-ERR_BINDING=1;
 if [[ "$(curl -k -s -o /dev/null -w "%{http_code}" \
   ${BASE_URI}/v2/service_instances/:instance_id/service_bindings/:binding_id?accepts_incomplete=true \
   -d '{ "service_id": "redis-service", "plan_id": "redis" }' \
   -X PUT -H 'Content-Type: application/json')" == "201" ]];
 then
-  ERR_BINDING=0;
+  echo "#### Binding request result:";
   echo "$(curl -k -s \
   ${BASE_URI}/v2/service_instances/:instance_id/service_bindings/:binding_id?accepts_incomplete=true \
   -d '{ "service_id": "redis-service", "plan_id": "redis" }' \
   -X PUT -H 'Content-Type: application/json')";
-  echo "Binding: OK";
+  echo "#### Binding: OK";
 else
-  echo "Binding: KO";
-fi
-
-ERR=1;
-if [[ ${ERR_CATALOG} -eq 0 ]] && [[ ${ERR_BINDING} -eq 0 ]];
-then
-  ERR=0;
+  ERR=1;
+  echo "ERROR: Binding: KO" >&2;
 fi
 
 exit ${ERR};
diff --git a/jobs/redis_check/templates/bin/run.erb b/jobs/redis_check/templates/bin/run.erb
--- a/jobs/redis_check/templates/bin/run.erb
+++ b/jobs/redis_check/templates/bin/run.erb
@@ -9,7 +9,6 @@
 
 ERR=0;
 CLI="/var/vcap/packages/redis/bin/redis-cli";
-
 REDIS_IP="127.0.0.1";
 <%- if master.p('bind') -%>
 REDIS_IP="<%= spec.ip %>";
@@ -55,15 +54,17 @@ fi
 #
 # Look up Redis instances
 #
-PING="$("${CLI}" \
+MSG="$("${CLI}" \
   -h "${REDIS_IP}" \
   -p "${REDIS_PORT}" \
   ${REDIS_CRED} \
   PING)";
 ERR=${?}
-if [[ ${ERR} -eq 0 ]] && [[ "${PING}" == "PONG" ]];
+if [[ ${ERR} -eq 0 ]] && [[ "${MSG}" == "PONG" ]];
 then
-  echo "Redis server at address [${REDIS_IP}] and port [${REDIS_PORT}] is available.";
+  echo -e "####\n#### Redis server at address [${REDIS_IP}] and port [${REDIS_PORT}] is available: \"${MSG}\".";
+else
+  echo "ERROR: Redis server at address [${REDIS_IP}] and port [${REDIS_PORT}] is unavailable: \"${MSG}\"." >&2;
 fi
 
 #
@@ -92,45 +93,53 @@ SENTINEL_CRED+=" --cacert ${TLS_CA_CERT_FILE}";
 
 for x in ${SENTINEL_ADDRESSES};
 do
-  PING="$("${CLI}" \
-    -h "${x}" \
-    -p "${SENTINEL_PORT}" \
+  MSG="$(${CLI} \
+    -h ${x} \
+    -p ${SENTINEL_PORT} \
     ${SENTINEL_CRED} \
     PING)";
-  ERR=${?}
-  if [[ ${ERR} -eq 0 ]] && [[ "${PING}" == "PONG" ]];
+  if [[ ${?} -eq 0 ]] && [[ "${MSG}" == "PONG" ]];
   then
-    echo "Redis Sentinel at address [${x}] and port [${SENTINEL_PORT}] is available.";
-    if [[ ${ERR} -eq 0 ]];
+    echo -e "####\n#### Redis Sentinel at address [${x}] and port [${SENTINEL_PORT}] is available: \"${MSG}\".";
+    MSG="$(${CLI} \
+      -h ${x} \
+      -p ${SENTINEL_PORT} \
+      ${SENTINEL_CRED} \
+      SENTINEL master <%= spec.deployment %>)";
+    if [[ ${?} -eq 0 ]];
     then
-      echo "Available master for Sentinel at ${x}:"
-      "${CLI}" \
-        -h "${x}" \
-        -p "${SENTINEL_PORT}" \
+      echo -e "####\n#### Available master for <%= spec.deployment %>: \"${MSG}\".";
+      MSG="$(${CLI} \
+        -h ${x} \
+        -p ${SENTINEL_PORT} \
         ${SENTINEL_CRED} \
-        SENTINEL master <%= spec.deployment %>;
-      ERR=${?};
-      if [[ ${ERR} -eq 0 ]];
-      then
-        echo "Available slaves for Sentinel at ${x}:"
-        "${CLI}" \
-          -h "${x}" \
-          -p "${SENTINEL_PORT}" \
-          ${SENTINEL_CRED} \
-          SENTINEL slaves <%= spec.deployment %>;
-        ERR=${?};
-      fi
-      if [[ ${ERR} -eq 0 ]];
-      then
-        echo "Available Sentinels for Sentinel at ${x}:"
-        "${CLI}" \
-          -h "${x}" \
-          -p "${SENTINEL_PORT}" \
-          ${SENTINEL_CRED} \
-          SENTINEL sentinels <%= spec.deployment %>;
-        ERR=${?};
-      fi
+        SENTINEL slaves <%= spec.deployment %>)";
+    else
+      ERR=1;
+      echo "ERROR: Unable to find Redis master for <%= spec.deployment %> from Redis Sentinel ${x}: \"${MSG}\"." >&2;
     fi
+    if [[ ${?} -eq 0 ]];
+    then
+      echo -e "####\n#### Available slaves for <%= spec.deployment %>: \"${MSG}\"."
+      MSG="$(${CLI} \
+        -h ${x} \
+        -p ${SENTINEL_PORT} \
+        ${SENTINEL_CRED} \
+        SENTINEL sentinels <%= spec.deployment %>)";
+    else
+      ERR=1;
+      echo "ERROR: Unable to find Redis slaves for <%= spec.deployment %> from Redis Sentinel ${x}: \"${MSG}\"." >&2;
+    fi
+    if [[ ${?} -eq 0 ]];
+    then
+      echo -e "####\n#### Available sentinels for <%= spec.deployment %>: \"${MSG}\".";
+    else
+      ERR=1;
+      echo "ERROR: Unable to find Redis Sentinel for <%= spec.deployment %> from Redis Sentinel ${x}: \"${MSG}\"." >&2;
+    fi
+  else
+    ERR=1;
+    echo "ERROR: Redis Sentinel at address [${x}] and port [${SENTINEL_PORT}] is unavailable: \"${MSG}\"." >&2;
   fi
 done
 <%- end -%>
@@ -140,10 +149,6 @@ done
 #
 CLI_CLUSTER_OPTS="";
 <%- if master.p('cluster_enabled').eql?('yes')
-  node_port=master.p('port')
-  if master.p('tls') && master.p('tls_cluster')
-    node_port=master.p('tls_port')
-  end
   master_addresses=''
   master.instances.each{ |x| master_addresses.concat(x.address).concat(' ') }
   master_instances=master.instances.length
@@ -178,14 +183,12 @@ SLAVE_INSTANCES="<%= slave_instances %>";
 REDIS_ADDRESSES="${MASTER_ADDRESSES} ${SLAVE_ADDRESSES}";
 REDIS_INSTANCES="<%= master_instances+slave_instances %>";
 REPLICAS_PER_NODE="<%= replicas_per_node %>";
-NODE_PORT="<%= node_port %>";
 
-echo "Initial masters addresses: [${MASTER_ADDRESSES}]";
-echo "Number of masters: [${MASTER_INSTANCES}]";
-echo "Initial slaves addresses: [${SLAVE_ADDRESSES}]";
-echo "Number of slaves: [${SLAVE_INSTANCES}]";
-echo "Replicas per master: [${REPLICAS_PER_NODE}]";
-echo "Nodes port: [${NODE_PORT}]";
+echo "#### Initial masters addresses: [${MASTER_ADDRESSES}]";
+echo "#### Number of masters: [${MASTER_INSTANCES}]";
+echo "#### Initial slaves addresses: [${SLAVE_ADDRESSES}]";
+echo "#### Number of slaves: [${SLAVE_INSTANCES}]";
+echo "#### Replicas per master: [${REPLICAS_PER_NODE}]";
 
 MSG="$("${CLI}" \
   -h "${REDIS_IP}" \
@@ -202,7 +205,7 @@ then
   do
     for j in ${REDIS_ADDRESSES};
     do
-      if [[ "${i%%@*}" == "${j}:${NODE_PORT}" ]];
+      if [[ "${i%%@*}" == "${j}:${REDIS_PORT}" ]];
       then
         ((AVAILABLE_NODES++));
       fi
@@ -210,34 +213,32 @@ then
   done
   if [[ ${REDIS_INSTANCES} -eq ${AVAILABLE_NODES} ]];
   then
-    echo "All required Redis nodes [${REDIS_INSTANCES}] are available in the cluster";
+    echo "#### All required Redis nodes [${REDIS_INSTANCES}] are available in the cluster.";
     AVAILABLE_NODES=$(echo "${MSG}" | awk '$3~/master/{print $2;}' | wc -l);
     if [[ ${MASTER_INSTANCES} -eq ${AVAILABLE_NODES} ]];
     then
-      echo "All required Redis master nodes [${MASTER_INSTANCES}] are available";
+      echo "#### All required Redis master nodes [${MASTER_INSTANCES}] are available.";
       ERR=0;
     else
-      echo "ERROR: The required Redis master nodes [${MASTER_INSTANCES}] is not equal to the available master nodes [${AVAILABLE_NODES}]" >&2;
+      echo "ERROR: The required Redis master nodes [${MASTER_INSTANCES}] is not equal to the available master nodes [${AVAILABLE_NODES}]." >&2;
       ERR=1;
     fi
     AVAILABLE_NODES=$(echo "${MSG}" | awk '$3~/slave/{print $2;}' | wc -l);
     if [[ ${SLAVE_INSTANCES} -eq ${AVAILABLE_NODES} ]];
     then
-      echo "All required Redis slave nodes [${SLAVE_INSTANCES}] are available";
+      echo "#### All required Redis slave nodes [${SLAVE_INSTANCES}] are available";
       ERR=0;
     else
-      echo "ERROR: The required Redis slave nodes [${SLAVE_INSTANCES}] is not equal to the available slave nodes [${AVAILABLE_NODES}]" >&2;
+      echo "ERROR: The required Redis slave nodes [${SLAVE_INSTANCES}] is not equal to the available slave nodes [${AVAILABLE_NODES}]." >&2;
       ERR=1;
     fi
   else
-    echo "ERROR: The required Redis nodes [${REDIS_INSTANCES}] is not equal to the available nodes [${AVAILABLE_NODES}]" >&2;
+    echo "ERROR: The required Redis nodes [${REDIS_INSTANCES}] is not equal to the available nodes [${AVAILABLE_NODES}]." >&2;
     ERR=1;
   fi
 else
   echo "ERROR: Redis CLUSTER NODES command failed: \"${MSG}\"." >&2;
-  ERR=1;
 fi
-
 CLI_CLUSTER_OPTS="-c";
 <%- end -%>
 
@@ -258,57 +259,48 @@ then
       SENTINEL get-master-addr-by-name <%= spec.deployment %>)";
     REDIS_IP="${REDIS_MASTER%%[[:space:]]*}";
     REDIS_PORT="${REDIS_MASTER#*[[:space:]]}";
+    echo -e "####\n#### CRUD operations to Redis master [${REDIS_IP}:${REDIS_PORT}] get from Sentinel [${x}] :";
 <%- end -%>
     CLI_OPTS="-h ${REDIS_IP} -p ${REDIS_PORT} ${REDIS_CRED} ${CLI_CLUSTER_OPTS}";
-    RESULT="$("${CLI}" \
-      ${CLI_OPTS} \
-      SET ${KV} ${KV})";
-    ERR=${?};
-    if [[ ${ERR} -eq 0 ]];
+    MSG="$(${CLI} ${CLI_OPTS} SET ${KV} ${KV})";
+    if [[ ${?} -eq 0 ]];
     then
-      echo "Create operation: succeed";
-      RESULT="$("${CLI}" \
-        ${CLI_OPTS} \
-        GET ${KV})";
-      ERR=${?};
-      if [[ ${ERR} -eq 0 ]] && [[ "${KV}" == "${RESULT}" ]];
+      echo "Create operation: succeed.";
+      MSG="$(${CLI} ${CLI_OPTS} GET ${KV})";
+      if [[ ${?} -eq 0 ]] && [[ "${KV}" == "${MSG}" ]];
       then
         echo "Read operation: succeed";
-         RESULT="$("${CLI}" \
-          ${CLI_OPTS} \
-          APPEND ${KV} ${KV})";
-        ERR=${?};
-        if [[ ${ERR} -eq 0 ]];
+        MSG="$(${CLI} ${CLI_OPTS} APPEND ${KV} ${KV})";
+        if [[ ${?} -eq 0 ]];
         then
           echo "Append operation: succeed";
-          RESULT="$("${CLI}" \
-            ${CLI_OPTS} \
-            GET ${KV})";
-          ERR=${?};
-          if [[ ${ERR} -eq 0 ]] && [[ "${KV}${KV}" == "${RESULT}" ]];
+          MSG="$(${CLI} ${CLI_OPTS} GET ${KV})";
+          if [[ ${?} -eq 0 ]] && [[ "${KV}${KV}" == "${MSG}" ]];
           then
-            echo "Update operation: succeed";
+            echo "Update operation: succeed.";
           else
-            echo "Update operation: failed: \"${RESULT}\".";
+            ERR=1;
+            echo "ERROR: Update operation: \"${MSG}\"." >&2;
           fi
         else
-          echo "Append operation: failed: \"${RESULT}\".";
+          ERR=1;
+          echo "ERROR: Append operation: \"${MSG}\"." >&2;
         fi
       else
-        echo "Read operation: failed: \"${RESULT}\".";
+        ERR=1;
+        echo "ERROR: Read operation: \"${MSG}\"." >&2;
       fi
-      RESULT="$("${CLI}" \
-        ${CLI_OPTS} \
-        DEL ${KV})";
-      ERR=${?};
-      if [[ ${ERR} -eq 0 ]];
+      MSG="$(${CLI} ${CLI_OPTS} DEL ${KV})";
+      if [[ ${?} -eq 0 ]];
       then
-        echo "Delete operation: succeed";
+        echo "Delete operation: succeed.";
       else
-        echo "Delete operation: failed: \"${RESULT}\".";
+        ERR=1;
+        echo "ERROR: Delete operation: \"${MSG}\"." >&2;
       fi
     else
-      echo "Create operation: failed: \"${RESULT}\".";
+      ERR=1;
+      echo "ERROR: Create operation: \"${MSG}\"." >&2;
     fi
 <%- if master.p('replication') && !sentinel.nil? -%>
   done
