1.0.2.2

diff --git a/jobs/redis_broker_check-1.5/templates/bin/run.erb b/jobs/redis_broker_check-1.5/templates/bin/run.erb
--- a/jobs/redis_broker_check-1.5/templates/bin/run.erb
+++ b/jobs/redis_broker_check-1.5/templates/bin/run.erb
@@ -1,43 +1,38 @@
 #!/bin/bash
 <%- broker=link('redis_broker_conn') -%>
 
+ERR=0;
 IP="127.0.0.1";
 <%- if broker.p('bind') -%>
 IP="<%= spec.ip %>";
 <%- end -%>
 BASE_URI="http://<%= broker.p('user') %>:<%= broker.p('password') %>@${IP}:<%= broker.p('port') %>";
 
-ERR_CATALOG=1;
 if [[ "$(curl -s -o /dev/null -I -w "%{http_code}" \
   ${BASE_URI}/v2/catalog)" == "200" ]];
 then
-  ERR_CATALOG=0;
+  echo "#### Catalog request result:";
   echo "$(curl ${BASE_URI}/v2/catalog)";
-  echo "Catalog: OK";
+  echo "#### Catalog: OK";
 else
-  echo "Catalog: KO";
+  ERR=1;
+  echo "ERROR: Catalog: KO" >&2;
 fi
 
-ERR_BINDING=1;
 if [[ "$(curl -s -o /dev/null -w "%{http_code}" \
   ${BASE_URI}/v2/service_instances/:instance_id/service_bindings/:binding_id?accepts_incomplete=true \
   -d '{ "service_id": "redis-service", "plan_id": "redis" }' \
   -X PUT -H 'Content-Type: application/json')" == "201" ]];
 then
-  ERR_BINDING=0;
+  echo "#### Binding request result:";
   echo "$(curl \
     ${BASE_URI}/v2/service_instances/:instance_id/service_bindings/:binding_id?accepts_incomplete=true \
     -d '{ "service_id": "redis-service", "plan_id": "redis" }' \
     -X PUT -H 'Content-Type: application/json')";
-  echo "Binding: OK";
+  echo "#### Binding: OK";
 else
-  echo "Binding: KO";
-fi
-
-ERR=1;
-if [[ ${ERR_CATALOG} -eq 0 ]] && [[ ${ERR_BINDING} -eq 0 ]];
-then
-  ERR=0;
+  ERR=1;
+  echo "ERROR: Binding: KO" >&2;
 fi
 
 exit ${ERR};
diff --git a/jobs/redis_check/templates/bin/run.erb b/jobs/redis_check/templates/bin/run.erb
--- a/jobs/redis_check/templates/bin/run.erb
+++ b/jobs/redis_check/templates/bin/run.erb
@@ -33,9 +33,9 @@ MSG="$(${CLI} \
 ERR=${?}
 if [[ ${ERR} -eq 0 ]] && [[ "${MSG}" == "PONG" ]];
 then
-  echo "Redis server at address [${REDIS_IP}] and port [${REDIS_PORT}] is available.";
+  echo "#### Redis server at address [${REDIS_IP}] and port [${REDIS_PORT}] is available: \"${MSG}\".";
 else
-  echo "ERROR: Redis server at address [${REDIS_IP}] and port [${REDIS_PORT}] is unavailable." >&2;
+  echo "ERROR: Redis server at address [${REDIS_IP}] and port [${REDIS_PORT}] is unavailable: \"${MSG}\"." >&2;
 fi
 
 #
@@ -65,7 +65,7 @@ do
     PING)";
   if [[ ${?} -eq 0 ]] && [[ "${MSG}" == "PONG" ]];
   then
-    echo "Redis Sentinel at address [${x}] and port [${SENTINEL_PORT}] is available: \"${MSG}\".";
+    echo "#### Redis Sentinel at address [${x}] and port [${SENTINEL_PORT}] is available: \"${MSG}\".";
     MSG="$(${CLI} \
       -h ${x} \
       -p ${SENTINEL_PORT} \
@@ -73,7 +73,7 @@ do
       SENTINEL master <%= spec.deployment %>)";
     if [[ ${?} -eq 0 ]];
     then
-      echo "Available master for <%= spec.deployment %>: \"${MSG}\".";
+      echo "#### Available master for <%= spec.deployment %>: \"${MSG}\".";
       MSG="$(${CLI} \
         -h ${x} \
         -p ${SENTINEL_PORT} \
@@ -85,7 +85,7 @@ do
     fi
     if [[ ${?} -eq 0 ]];
     then
-      echo "Available slaves for <%= spec.deployment %>: \"${MSG}\"."
+      echo "#### Available slaves for <%= spec.deployment %>: \"${MSG}\"."
       MSG="$(${CLI} \
         -h ${x} \
         -p ${SENTINEL_PORT} \
@@ -97,7 +97,7 @@ do
     fi
     if [[ ${?} -eq 0 ]];
     then
-      echo "Available sentinels for <%= spec.deployment %>: \"${MSG}\".";
+      echo "#### Available sentinels for <%= spec.deployment %>: \"${MSG}\".";
     else
       ERR=1;
       echo "ERROR: Unable to find Redis Sentinel for <%= spec.deployment %> from Redis Sentinel ${x}: \"${MSG}\"." >&2;
@@ -149,11 +149,11 @@ REDIS_ADDRESSES="${MASTER_ADDRESSES} ${SLAVE_ADDRESSES}";
 REDIS_INSTANCES="<%= master_instances+slave_instances %>";
 REPLICAS_PER_NODE="<%= replicas_per_node %>";
 
-echo "Initial masters addresses: [${MASTER_ADDRESSES}]";
-echo "Number of masters: [${MASTER_INSTANCES}]";
-echo "Initial slaves addresses: [${SLAVE_ADDRESSES}]";
-echo "Number of slaves: [${SLAVE_INSTANCES}]";
-echo "Replicas per master: [${REPLICAS_PER_NODE}]";
+echo "#### Initial masters addresses: [${MASTER_ADDRESSES}]";
+echo "#### Number of masters: [${MASTER_INSTANCES}]";
+echo "#### Initial slaves addresses: [${SLAVE_ADDRESSES}]";
+echo "#### Number of slaves: [${SLAVE_INSTANCES}]";
+echo "#### Replicas per master: [${REPLICAS_PER_NODE}]";
 
 MSG="$("${CLI}" \
   -h "${REDIS_IP}" \
@@ -163,8 +163,7 @@ MSG="$("${CLI}" \
 ERR=${?};
 if [[ ${ERR} -eq 0 ]];
 then
-  echo "Redis CLUSTER NODES command results:";
-  echo "${MSG}";
+  echo "#### Redis CLUSTER NODES command results: \"${MSG}\"".
   AVAILABLE_NODES=0;
   for i in $(echo "${MSG}" | awk '{print $2;}');
   do
@@ -178,11 +177,11 @@ then
   done
   if [[ ${REDIS_INSTANCES} -eq ${AVAILABLE_NODES} ]];
   then
-    echo "All required Redis nodes [${REDIS_INSTANCES}] are available in the cluster.";
+    echo "#### All required Redis nodes [${REDIS_INSTANCES}] are available in the cluster.";
     AVAILABLE_NODES=$(echo "${MSG}" | awk '$3~/master/{print $2;}' | wc -l);
     if [[ ${MASTER_INSTANCES} -eq ${AVAILABLE_NODES} ]];
     then
-      echo "All required Redis master nodes [${MASTER_INSTANCES}] are available.";
+      echo "#### All required Redis master nodes [${MASTER_INSTANCES}] are available.";
       ERR=0;
     else
       echo "ERROR: The required Redis master nodes [${MASTER_INSTANCES}] is not equal to the available master nodes [${AVAILABLE_NODES}]." >&2;
@@ -191,7 +190,7 @@ then
     AVAILABLE_NODES=$(echo "${MSG}" | awk '$3~/slave/{print $2;}' | wc -l);
     if [[ ${SLAVE_INSTANCES} -eq ${AVAILABLE_NODES} ]];
     then
-      echo "All required Redis slave nodes [${SLAVE_INSTANCES}] are available.";
+      echo "#### All required Redis slave nodes [${SLAVE_INSTANCES}] are available.";
       ERR=0;
     else
       echo "ERROR: The required Redis slave nodes [${SLAVE_INSTANCES}] is not equal to the available slave nodes [${AVAILABLE_NODES}]." >&2;
@@ -223,7 +222,7 @@ then
       SENTINEL get-master-addr-by-name <%= spec.deployment %>)";
     REDIS_IP="${REDIS_MASTER%%[[:space:]]*}";
     REDIS_PORT="${REDIS_MASTER#*[[:space:]]}";
-    echo "CRUD operations to Redis master [${REDIS_IP}:${REDIS_PORT}] get from Sentinel [${x}] :";
+    echo "#### CRUD operations to Redis master [${REDIS_IP}:${REDIS_PORT}] get from Sentinel [${x}] :";
 <%- end -%>
     CLI_OPTS="${REDIS_CRED} ${CLI_CLUSTER_OPTS} -h ${REDIS_IP} -p ${REDIS_PORT}";
     MSG="$(${CLI} ${CLI_OPTS} SET ${KV} ${KV})";
