1.0.2.2

diff --git a/jobs/redis_sentinel/templates/bin/pre-stop.erb b/jobs/redis_sentinel/templates/bin/pre-stop.erb
--- a/jobs/redis_sentinel/templates/bin/pre-stop.erb
+++ b/jobs/redis_sentinel/templates/bin/pre-stop.erb
@@ -14,9 +14,9 @@ IP="<%= spec.ip %>";
 <%- end -%>
 PORT="<%= sentinel.p('port') %>";
 CRED="";
-<%- sentinel.if_p('password') do |password|
-    unless password.to_s.empty? -%>
-CRED="-a <%= password %>";
+<%- sentinel.if_p('password') do |x|
+    unless x.to_s.empty? -%>
+CRED="-a <%= x %>";
 <%- end
   end -%>
 
@@ -36,7 +36,10 @@ else
       [[ $(cp -f "${CONF_FILE}" "${STORE_DIR}/config/.") -ne 0 ]];
     then
       ERR=1;
-      echo "ERROR: Unable to copy ${CONF_FILE} to ${STORE_DIR}/config/.${STORE_DIR}/config" >&2;
+      ERR=1;
+      echo "ERROR: Unable to copy ${CONF_FILE} to ${STORE_DIR}/config/." >&2;
+    else
+      echo "Redis Sentinel configuration ${CONF_FILE} is backuped in ${STORE_DIR}/config/.";
     fi
   fi
 fi
