1.0.3.1

diff --git a/jobs/redis/templates/bin/post-start.erb b/jobs/redis/templates/bin/post-start.erb
--- a/jobs/redis/templates/bin/post-start.erb
+++ b/jobs/redis/templates/bin/post-start.erb
@@ -5,8 +5,28 @@
   sentinel_slave=nil
   if_link('sentinel_slave_conn'){ |x| sentinel_slave=x } -%>
 
+function wait_replica_sync {
+  local is_connected=0;
+  while [[ ${is_connected} -eq 0 ]] && [[ ${ERR} -eq 0 ]];
+  do
+    sleep "${DEPLAY}";
+    MSG="$("${CLI}" \
+      -h ${REDIS_IP} \
+      -p ${REDIS_PORT} \
+      ${REDIS_CRED} \
+      ROLE)";
+    ERR=${?};
+    if [[ ${ERR} -eq 0 ]] && \
+      [[ "connected" == "$(echo -e "${MSG}"|grep "connected")" ]];
+    then
+      is_connected=1;
+      echo "Redis replica [${REDIS_IP}:${REDIS_PORT}] is connected";
+    fi
+  done
+}
+
 ERR=0;
-<%- if !sentinel.nil? && master.p('replication') -%>
+DEPLAY="1";
 CLI="/var/vcap/packages/redis/bin/redis-cli";
 REDIS_IP="127.0.0.1";
 <%- if master.p('bind') -%>
@@ -28,8 +48,8 @@ TLS_KEY_FILE="${TLS_KEYS_DIR}/<%= p('tls_key_file') %>";
 REDIS_CRED+=" --key ${TLS_KEY_FILE}";
 TLS_CA_CERT_FILE="${TLS_KEYS_DIR}/<%= p('tls_ca_cert_file') %>";
 REDIS_CRED+=" --cacert ${TLS_CA_CERT_FILE}";
-<%- end -%>
-
+<%- end
+  if !sentinel.nil? && master.p('replication') -%>
 SENTINEL_PORT="<%= sentinel.p('port') %>";
 SENTINEL_CRED="";
 <%- sentinel.if_p('password') do |x|
@@ -56,41 +76,53 @@ i=0;
 is_replica=0;
 for x in ${SENTINEL_ADDRESSES};
 do
-  MSG="$("${CLI}" \
-    -h "${x}" \
-    -p "${SENTINEL_PORT}" \
-    ${SENTINEL_CRED} \
-    SENTINEL GET-MASTER-ADDR-BY-NAME <%= spec.deployment %>)";
-  if [[ ${?} -eq 0 ]] && \
-    [[ -n "${MSG}" ]] && \
-    [[ "${REDIS_IP}" != "$(echo -e "${MSG}"|grep "${REDIS_IP}")" || \
-    "${REDIS_PORT}" != "$(echo -e "${MSG}"|grep "${REDIS_PORT}")" ]];
+  if [[ "${x}" != "${REDIS_IP}" ]];
   then
-    is_replica=1;
-    echo "Redis instance [${REDIS_IP}:${REDIS_PORT}] is a replica.";
-    break;
+    MSG="$("${CLI}" \
+      -h "${x}" \
+      -p "${SENTINEL_PORT}" \
+      ${SENTINEL_CRED} \
+      SENTINEL GET-MASTER-ADDR-BY-NAME <%= spec.deployment %>)";
+    if [[ ${?} -eq 0 ]] && \
+      [[ -n "${MSG}" ]] && \
+      [[ "${REDIS_IP}" != "$(echo -e "${MSG}"|grep "${REDIS_IP}")" || \
+      "${REDIS_PORT}" != "$(echo -e "${MSG}"|grep "${REDIS_PORT}")" ]];
+    then
+      is_replica=1;
+      echo "Redis instance [${REDIS_IP}:${REDIS_PORT}] is a replica.";
+      break;
+    fi
   fi
   ((i++));
 done
 
 if [[ ${i} -lt ${SENTINEL_INSTANCES} ]] && [[ ${is_replica} -eq 1 ]];
 then
-  is_connected=0;
-  while [[ ${is_connected} -eq 0 ]] && [[ ${ERR} -eq 0 ]];
-  do
-    MSG="$("${CLI}" \
+  wait_replica_sync;
+fi
+<%- end
+  if master.p('cluster_enabled').eql?('yes') -%>
+MYID="$("${CLI}" \
       -h ${REDIS_IP} \
       -p ${REDIS_PORT} \
       ${REDIS_CRED} \
-      ROLE)";
-    ERR=${?};
-    if [[ ${ERR} -eq 0 ]] && \
-      [[ "connected" == "$(echo -e "${MSG}"|grep "connected")" ]];
-    then
-      is_connected=1;
-      echo "Redis replica [${REDIS_IP}:${REDIS_PORT}] is connected";
-    fi
-  done
+      CLUSTER MYID)";
+ERR=${?};
+if [[ ${ERR} -eq 0 ]];
+then
+  MSG="$("${CLI}" \
+      -h ${REDIS_IP} \
+      -p ${REDIS_PORT} \
+      ${REDIS_CRED} \
+      CLUSTER REPLICAS ${MYID})";
+  if [[ ${?} -ne 0 ]];
+  then
+    wait_replica_sync;
+  else
+    echo "Redis instance [${REDIS_IP}:${REDIS_PORT}] is a master.";
+  fi
+else
+  echo "ERROR: Redis CLUSTER MYID command failed: \"${MYID}\"." >&2;
 fi
 <%- end -%>
 
