1.0.2.2

diff --git a/jobs/redis/templates/bin/post-deploy.erb b/jobs/redis/templates/bin/post-deploy.erb
--- a/jobs/redis/templates/bin/post-deploy.erb
+++ b/jobs/redis/templates/bin/post-deploy.erb
@@ -1,89 +1,85 @@
 #!/bin/bash
-<%
-  master=link('redis_conn')
+<%- master=link('redis_conn')
   if_link('master_conn'){ |x| master=x }
   slave=link('redis_conn')
-  if_link('slave_conn'){ |x| slave=x }
-%>
+  if_link('slave_conn'){ |x| slave=x } -%>
 
 ERR=0;
-
-<% if master.p('cluster_enabled').eql?('yes') && master.instances.find{ |x| x.bootstrap }.address.eql?(spec.address) %>
-
-REDIS_HOME="/var/vcap/packages/redis";
-REDIS_CLI="${REDIS_HOME}/bin/redis-cli";
-
+<%- if master.p('cluster_enabled').eql?('yes') && master.instances.find{ |x| x.bootstrap }.address.eql?(spec.address) -%>
+CLI="/var/vcap/packages/redis/bin/redis-cli";
 REDIS_IP="127.0.0.1";
-<% if master.p('bind') %>
+<%- if master.p('bind') -%>
 REDIS_IP="<%= spec.ip %>";
-<% end %>
+<%- end -%>
 REDIS_PORT="<%= master.p('port') %>";
-
-REDIS_PASSWORD="";
-<%
-  master.if_p('password') do |password|
-    unless password.to_s.empty? %>
-REDIS_PASSWORD="-a <%= password %>";
-<%  end
+REDIS_CRED="";
+<%- master.if_p('password') do |password|
+    unless password.to_s.empty? -%>
+REDIS_CRED="-a <%= password %>";
+<%- end
   end
-%>
-
-<%
-  addresses=''
-  master.instances.each{ |x| addresses.concat(x.address).concat(' ') }
-  instances=master.instances.length
-%>
-REDIS_MASTER_ADDRESSES="<%= addresses %>";
-REDIS_MASTER_INSTANCES="<%= instances %>";
-<%
+  master_addresses=''
+  master.instances.each{ |x| master_addresses.concat(x.address).concat(' ') }
+  master_instances=master.instances.length
+  replicas_per_node=master.p('cluster_replicas_per_node').to_i
   slaves_addresses=''
   slave_instances=0
-  if !slave.instances[0].name.eql?(master.instances[0].name)
-    slave.instances.each{ |x| slaves_addresses.concat(x.address).concat(' ') }
-    slave_instances=slave.instances.length
+  if !slave.nil?
+    if replicas_per_node>0
+      slave.instances.each{ |x| slaves_addresses.concat(x.address).concat(' ') }
+      slave_instances=slave.instances.length
+    else
+      slave.instances.each{ |x| master_addresses.concat(x.address).concat(' ') }
+      master_instances+=slave.instances.length
+      replicas_per_node=0
+    end
+  elsif replicas_per_node>0
+    if master_instances>replicas_per_node
+      addresses=master_addresses.split
+      master_instances=master_instances.div(replicas_per_node+1)
+      master_addresses=addresses.slice(0..master_instances-1).join(' ')
+      slaves_addresses=addresses.slice(master_instances..-1)
+      slave_instances=slaves_addresses.length
+      slaves_addresses=slaves_addresses.join(' ')
+    else
+      replicas_per_node=0
+    end
   end
-  addresses.concat(slaves_addresses)
-  instances+=slave_instances
-%>
-REDIS_SLAVE_ADDRESSES="<%= slaves_addresses %>";
-REDIS_SLAVE_INSTANCES="<%= slave_instances %>";
-REDIS_ADDRESSES="<%= addresses %>";
-REDIS_INSTANCES="<%= instances %>";
+  if replicas_per_node>0 && master_instances*replicas_per_node>slave_instances
+    STDERR.puts "WARNING: Not enough slave: masters [#{master_instances}], slaves [#{slave_instances}], slaves per master [#{replicas_per_node}]"
+  end -%>
+MASTER_ADDRESSES="<%= master_addresses %>";
+MASTER_INSTANCES="<%= master_instances %>";
+SLAVE_ADDRESSES="<%= slaves_addresses %>";
+SLAVE_INSTANCES="<%= slave_instances %>";
+REDIS_ADDRESSES="${MASTER_ADDRESSES} ${SLAVE_ADDRESSES}";
+REDIS_INSTANCES="<%= master_instances+slave_instances %>";
+REPLICAS_PER_NODE="<%= replicas_per_node %>";
+NODE_PORT="<%= node_port %>";
 
-REDIS_SLAVE_PER_INSTANCE="";
-SLAVE_PER_INSTANCE="<%= master.p('cluster_replicas_per_node') %>";
-if [[ ${SLAVE_PER_INSTANCE} -gt 0 ]];
-then
-  REDIS_SLAVE_PER_INSTANCE="--cluster-replicas ${SLAVE_PER_INSTANCE}";
-else
-  SLAVE_PER_INSTANCE=0;
-fi
+echo "Masters addresses: [${MASTER_ADDRESSES}]";
+echo "Number of masters: [${MASTER_INSTANCES}]";
+echo "Slaves addresses: [${SLAVE_ADDRESSES}]";
+echo "Number of slaves: [${SLAVE_INSTANCES}]";
+echo "Replicas per master: [${REPLICAS_PER_NODE}]";
+echo "Nodes port: [${NODE_PORT}]";
 
-REDIS_MASTER_NODES="";
-for i in ${REDIS_MASTER_ADDRESSES};
-do
-  REDIS_MASTER_NODES+=" ${i}:${REDIS_PORT}";
-done
-
-REDIS_SLAVE_NODES="";
-for i in ${REDIS_SLAVE_ADDRESSES};
-do
-  REDIS_SLAVE_NODES+=" ${i}:${REDIS_PORT}";
-done
-
-REDIS_CLUSTER_NODES_COMMAND="$(${REDIS_CLI} ${REDIS_PASSWORD} \
-  -h ${REDIS_IP} -p ${REDIS_PORT} CLUSTER NODES)";
+MSG="$("${CLI}" \
+  -h "${REDIS_IP}" \
+  -p "${REDIS_PORT}" \
+  ${REDIS_CRED} \
+  CLUSTER NODES)";
 ERR=${?};
 if [[ ${ERR} -eq 0 ]];
 then
   echo "Redis CLUSTER NODES command results:";
-  echo "${REDIS_CLUSTER_NODES_COMMAND}";
+  echo "${MSG}";
   AVAILABLE_NODES=0;
-  for i in $(echo "${REDIS_CLUSTER_NODES_COMMAND}" | awk '{print $2;}');
+  for i in $(echo "${MSG}" | awk '{print $2;}');
   do
     for j in ${REDIS_ADDRESSES};
     do
-      if [[ "${i%%@*}" == "${j}:${REDIS_PORT}" ]];
+      if [[ "${i%%@*}" == "${j}:${NODE_PORT}" ]];
       then
         ((AVAILABLE_NODES++));
       fi
@@ -91,9 +87,11 @@ then
   done
   if [[ ${REDIS_INSTANCES} -eq ${AVAILABLE_NODES} ]];
   then
-    echo "All requested nodes are already in a cluster.";
+    echo "ERROR: All requested nodes are already in a cluster." >&2;
     exit 0;
   fi
+else
+  echo "ERROR: Redis CLUSTER NODES command failed: \"${MSG}\"." >&2;
 fi
 
 AVAILABLE_NODES=0;
@@ -102,7 +100,11 @@ do
   AVAILABLE_NODES=0;
   for i in ${REDIS_ADDRESSES};
   do
-    PING="$(${REDIS_CLI} -h ${i} -p ${REDIS_PORT} ${REDIS_PASSWORD} PING)";
+    PING="$("${CLI}" \
+      -h "${i}" \
+      -p "${REDIS_PORT}" \
+      ${REDIS_CRED} \
+      PING)";
     if [[ ${?} -eq 0 ]] && [[ "${PING}" == "PONG" ]];
     then
       ((AVAILABLE_NODES++));
@@ -112,92 +114,189 @@ done
 
 if [[ ${REDIS_INSTANCES} -eq ${AVAILABLE_NODES} ]];
 then
-<% if slave.instances[0].name.eql?(master.instances[0].name) %>
-  if [[ $(( ${REDIS_MASTER_INSTANCES}%(${SLAVE_PER_INSTANCE}+1) )) -ne 0 ]];
-  then
-    echo "WARNING: Not enough slave: master [${REDIS_MASTER_INSTANCES}], slave per master [${SLAVE_PER_INSTANCE}]" >&2;
-  fi
-  ${REDIS_CLI} \
-    ${REDIS_PASSWORD} \
-    --cluster create ${REDIS_MASTER_NODES} ${REDIS_SLAVE_NODES} \
-    ${REDIS_SLAVE_PER_INSTANCE} <<< "yes";
+  MASTER_NODES="";
+  for i in ${MASTER_ADDRESSES};
+  do
+    MASTER_NODES+=" ${i}:${NODE_PORT}";
+  done
+  "${CLI}" \
+    ${REDIS_CRED} \
+    --cluster create ${MASTER_NODES} <<< "yes";
   ERR=${?};
-<% else %>
-  if [[ ${REDIS_SLAVE_INSTANCES} -lt ${REDIS_MASTER_INSTANCES}*${SLAVE_PER_INSTANCE} ]];
+  if [[ ${ERR} -eq 0 ]] && [[ ${REPLICAS_PER_NODE} -gt 0 ]];
   then
-    echo "WARNING: Not enough slave: master [${REDIS_MASTER_INSTANCES}], slave [${REDIS_SLAVE_INSTANCES}], slave per master [${SLAVE_PER_INSTANCE}]" >&2;
-  fi
-  REDIS_NODES="${REDIS_MASTER_NODES}";
-  if [[ ${SLAVE_PER_INSTANCE} -eq 0 ]];
-  then
-    REDIS_NODES="${REDIS_MASTER_NODES} ${REDIS_SLAVE_NODES}";
-  fi
-  ${REDIS_CLI} \
-    ${REDIS_PASSWORD} \
-    --cluster create ${REDIS_NODES} <<< "yes";
-  ERR=${?};
-  if [[ ${ERR} -eq 0 ]] && [[ ${SLAVE_PER_INSTANCE} -gt 0 ]];
-  then
-    for i in ${REDIS_MASTER_ADDRESSES};
+    k=${SLAVE_INSTANCES};
+    l="${SLAVE_ADDRESSES}";
+    for i in ${MASTER_ADDRESSES};
     do
-      MASTER_ID="$(${REDIS_CLI} \
-        ${REDIS_PASSWORD} \
-        -h ${i} -p ${REDIS_PORT} \
+      echo "Associating replicas to [${i}]...";
+      MASTER_ID="$("${CLI}" \
+        -h "${i}" \
+        -p "${REDIS_PORT}" \
+        ${REDIS_CRED} \
         CLUSTER MYID)";
       ERR=${?};
       j=0;
-      while [[ ${ERR} -eq 0 ]] && \
-        [[ -n "${REDIS_SLAVE_ADDRESSES}" ]] && \
-        [[ ${j} -lt ${SLAVE_PER_INSTANCE} ]];
+      while [[ ${ERR} -eq 0 ]] && [[ ${k} -gt 0 ]] && \
+        [[ ${j} -lt ${REPLICAS_PER_NODE} ]];
       do
-        ${REDIS_CLI} \
-          ${REDIS_PASSWORD} \
-          --cluster add-node ${REDIS_SLAVE_ADDRESSES%% *}:${REDIS_PORT} \
-          ${i}:${REDIS_PORT} \
+        echo "Associate replica [${l%% *}] to [${i}]";
+        "${CLI}" \
+          ${REDIS_CRED} \
+          --cluster add-node ${l%% *}:${NODE_PORT} \
+          ${i}:${NODE_PORT} \
           --cluster-slave \
           --cluster-master-id ${MASTER_ID} <<< "yes";
         ERR=${?};
-        REDIS_SLAVE_ADDRESSES="${REDIS_SLAVE_ADDRESSES#* }";
+        l="${l#* }";
         ((j++));
+        ((k--));
       done
     done
 
-    while [[ ${ERR} -eq 0 ]] && \
-      [[ -n "${REDIS_SLAVE_ADDRESSES}" ]];
+    while [[ ${ERR} -eq 0 ]] && [[ ${k} -gt 0 ]];
     do
-      for i in ${REDIS_MASTER_ADDRESSES};
+      for i in ${MASTER_ADDRESSES};
       do
-        MASTER_ID="$(${REDIS_CLI} \
-          ${REDIS_PASSWORD} \
-          -h ${i} -p ${REDIS_PORT} \
+        echo "Associate replica [${l%% *}] to [${i}]";
+        MASTER_ID="$("${CLI}" \
+          -h "${i}" \
+          -p "${REDIS_PORT}" \
+          ${REDIS_CRED} \
           CLUSTER MYID)";
         ERR=${?};
-        ${REDIS_CLI} \
-          ${REDIS_PASSWORD} \
-          --cluster add-node ${REDIS_SLAVE_ADDRESSES%% *}:${REDIS_PORT} \
-          ${i}:${REDIS_PORT} \
+        "${CLI}" \
+          ${REDIS_CRED} \
+          --cluster add-node ${l%% *}:${NODE_PORT} \
+          ${i}:${NODE_PORT} \
           --cluster-slave \
           --cluster-master-id ${MASTER_ID} <<< "yes";
         ERR=${?};
-        REDIS_SLAVE_ADDRESSES="${REDIS_SLAVE_ADDRESSES#* }";
-        if [[ -z "${REDIS_SLAVE_ADDRESSES}" ]];
+        l="${l#* }";
+        ((k--));
+        if [[ ${k} -le 0 ]];
         then
           break;
         fi
       done
     done
   fi
-<% end %>
-  REDIS_CLUSTER_NODES_COMMAND="$(${REDIS_CLI} ${REDIS_PASSWORD} \
-    -h ${REDIS_IP} -p ${REDIS_PORT} CLUSTER NODES)";
+
+  #
+  # Check built cluster
+  #
+  AVAILABLE_NODES=0;
+  AVAILABLE_MASTER_NODES=0;
+  AVAILABLE_SLAVE_NODES=0;
+  while [[ ${REDIS_INSTANCES} -gt ${AVAILABLE_NODES} ]] \
+    || [[ ${MASTER_INSTANCES} -gt ${AVAILABLE_MASTER_NODES} ]] \
+    || [[ ${SLAVE_INSTANCES} -gt ${AVAILABLE_SLAVE_NODES} ]];
+  do
+    MSG="$("${CLI}" \
+      -h "${REDIS_IP}" \
+      -p "${REDIS_PORT}" \
+      ${REDIS_CRED} \
+      CLUSTER NODES)";
+    ERR=${?};
+    if [[ ${ERR} -eq 0 ]];
+    then
+      #
+      # Check all nodes
+      #
+      AVAILABLE_NODES=0;
+      for i in $(echo "${MSG}" | awk '{print $2;}');
+      do
+        for j in ${REDIS_ADDRESSES};
+        do
+          if [[ "${i%%@*}" == "${j}:${NODE_PORT}" ]];
+          then
+            ((AVAILABLE_NODES++));
+          fi
+        done
+      done
+      #
+      # Check master nodes
+      #
+      AVAILABLE_MASTER_NODES=0;
+      for i in $(echo "${MSG}" | awk '$3~/master/{print $2;}');
+      do
+        for j in ${MASTER_ADDRESSES};
+        do
+          if [[ "${i%%@*}" == "${j}:${NODE_PORT}" ]];
+          then
+            ((AVAILABLE_MASTER_NODES++));
+          fi
+        done
+      done
+      #
+      # Check slave nodes
+      #
+      AVAILABLE_SLAVE_NODES=0;
+      for i in $(echo "${MSG}" | awk '$3~/slave/{print $2;}');
+      do
+        for j in ${SLAVE_ADDRESSES};
+        do
+          if [[ "${i%%@*}" == "${j}:${NODE_PORT}" ]];
+          then
+            ((AVAILABLE_SLAVE_NODES++));
+          fi
+        done
+      done
+    else
+      echo "ERROR: Redis CLUSTER NODES command failed: \"${MSG}\"." >&2;
+      exit ${ERR};
+    fi
+  done
+  MSG="$("${CLI}" \
+    -h "${REDIS_IP}" \
+    -p "${REDIS_PORT}" \
+    ${REDIS_CRED} \
+    CLUSTER NODES)";
   ERR=${?};
   if [[ ${ERR} -eq 0 ]];
   then
     echo "Redis CLUSTER NODES command results:";
-    echo "${REDIS_CLUSTER_NODES_COMMAND}";
+    echo "${MSG}";
+    AVAILABLE_NODES=0;
+    for i in $(echo "${MSG}" | awk '{print $2;}');
+    do
+      for j in ${REDIS_ADDRESSES};
+      do
+        if [[ "${i%%@*}" == "${j}:${NODE_PORT}" ]];
+        then
+          ((AVAILABLE_NODES++));
+        fi
+      done
+    done
+    if [[ ${REDIS_INSTANCES} -eq ${AVAILABLE_NODES} ]];
+    then
+      echo "All required Redis nodes [${REDIS_INSTANCES}] are available in the cluster";
+      AVAILABLE_NODES=$(echo "${MSG}" | awk '$3~/master/{print $2;}' | wc -l);
+      if [[ ${MASTER_INSTANCES} -eq ${AVAILABLE_NODES} ]];
+      then
+        echo "All required Redis master nodes [${MASTER_INSTANCES}] are available";
+        ERR=0;
+      else
+        echo "ERROR: The required Redis master nodes [${MASTER_INSTANCES}] is not equal to the available master nodes [${AVAILABLE_NODES}]" >&2;
+        ERR=1;
+      fi
+      AVAILABLE_NODES=$(echo "${MSG}" | awk '$3~/slave/{print $2;}' | wc -l);
+      if [[ ${SLAVE_INSTANCES} -eq ${AVAILABLE_NODES} ]];
+      then
+        echo "All required Redis slave nodes [${SLAVE_INSTANCES}] are available";
+        ERR=0;
+      else
+        echo "ERROR: The required Redis slave nodes [${SLAVE_INSTANCES}] is not equal to the available slave nodes [${AVAILABLE_NODES}]" >&2;
+        ERR=1;
+      fi
+    else
+      echo "ERROR: The required Redis nodes [${REDIS_INSTANCES}] is not equal to the available nodes [${AVAILABLE_NODES}]" >&2;
+      ERR=1;
+    fi
+  else
+    echo "ERROR: Redis CLUSTER NODES command failed: \"${MSG}\"." >&2;
   fi
 fi
-
-<% end %>
+<%- end -%>
 
 exit ${ERR};
diff --git a/jobs/redis_check/templates/bin/run.erb b/jobs/redis_check/templates/bin/run.erb
--- a/jobs/redis_check/templates/bin/run.erb
+++ b/jobs/redis_check/templates/bin/run.erb
@@ -1,130 +1,151 @@
 #!/bin/bash
-<%
-  master=link('redis_conn')
+<%- master=link('redis_conn')
   if_link('master_conn'){ |x| master=x }
   slave=link('redis_conn')
   if_link('slave_conn'){ |x| slave=x }
   sentinel=nil
-  if_link('redis_sentinel_conn'){ |x| sentinel=x }
-%>
+  if_link('SENTINEL_conn'){ |x| sentinel=x }
+  sentinel_slave=nil
+  if_link('sentinel_slave_conn'){ |x| sentinel_slave=x } -%>
 
 ERR=0;
-
-REDIS_HOME="/var/vcap/packages/redis";
-REDIS_CLI="${REDIS_HOME}/bin/redis-cli";
+CLI="/var/vcap/packages/redis/bin/redis-cli";
 
 REDIS_IP="127.0.0.1";
-<% if master.p('bind') %>
+<%- if master.p('bind') -%>
 REDIS_IP="<%= spec.ip %>";
-<% end %>
+<%- end -%>
 REDIS_PORT="<%= master.p('port') %>";
 
 REDIS_PASSWORD="";
-<%
-  master.if_p('password') do |password|
-    unless password.to_s.empty? %>
+<%- master.if_p('password') do |password|
+    unless password.to_s.empty? -%>
 REDIS_PASSWORD="-a <%= password %>";
-<%  end
-  end
-%>
+<%- end
+  end -%>
 
 #
 # Look up Redis instance
 #
-PING="$(${REDIS_CLI} ${REDIS_PASSWORD} -h ${REDIS_IP} -p ${REDIS_PORT} PING)";
+MSG="$(${CLI} ${REDIS_PASSWORD} -h ${REDIS_IP} -p ${REDIS_PORT} PING)";
 ERR=${?}
-if [[ ${ERR} -eq 0 ]] && [[ "${PING}" == "PONG" ]];
+if [[ ${ERR} -eq 0 ]] && [[ "${MSG}" == "PONG" ]];
 then
   echo "Redis server at address [${REDIS_IP}] and port [${REDIS_PORT}] is available.";
+else
+  echo "ERROR: Redis server at address [${REDIS_IP}] and port [${REDIS_PORT}] is unavailable." >&2;
 fi
 
 #
 # Look up Redis Sentinel instance
 #
-<%
-  if master.p('replication') && !sentinel.nil? %>
-REDIS_SENTINEL_IP="127.0.0.1";
-<%
-    if sentinel.p('bind') %>
-REDIS_SENTINEL_IP="<%= spec.ip %>";
-<%
-    end %>
-REDIS_SENTINEL_PORT="<%= sentinel.p('port') %>";
+<%- if master.p('replication') && !sentinel.nil?
+  sentinel_addresses=''
+  sentinel.instances.each{ |x| sentinel_addresses.concat(x.address).concat(' ') }
+  if !sentinel_slave.nil?
+    sentinel_slave.instances.each{ |x| sentinel_addresses.concat(x.address).concat(' ') }
+  end -%>
+SENTINEL_ADDRESSES="<%= sentinel_addresses %>";
+SENTINEL_PORT="<%= sentinel.p('port') %>";
+SENTINEL_PASSWORD="";
+<%- sentinel.if_p('password') do |password|
+    unless password.to_s.empty? -%>
+SENTINEL_PASSWORD="-a <%= password %>";
+<%- end
+  end -%>
 
-REDIS_SENTINEL_PASSWORD="";
-<%
-  sentinel.if_p('password') do |password|
-    unless password.to_s.empty? %>
-REDIS_SENTINEL_PASSWORD="-a <%= password %>";
-<%  end
-  end
-%>
-PING="$(${REDIS_CLI} ${REDIS_SENTINEL_PASSWORD} \
-  -h ${REDIS_SENTINEL_IP} -p ${REDIS_SENTINEL_PORT} PING)";
-ERR=${?}
-if [[ ${ERR} -eq 0 ]] && [[ "${PING}" == "PONG" ]];
-then
-  echo "Redis Sentinel at address [${REDIS_SENTINEL_IP}] and port [${REDIS_SENTINEL_PORT}] is available.";
-fi
-echo "Available master:"
-${REDIS_CLI} ${REDIS_SENTINEL_PASSWORD} \
-  -h ${REDIS_SENTINEL_IP} -p ${REDIS_SENTINEL_PORT} SENTINEL master <%= spec.deployment %>;
-ERR=${?};
-if [[ ${ERR} -eq 0 ]];
-then
-  echo "Available slaves:"
-  ${REDIS_CLI} ${REDIS_SENTINEL_PASSWORD} \
-    -h ${REDIS_SENTINEL_IP} -p ${REDIS_SENTINEL_PORT} SENTINEL slaves <%= spec.deployment %>;
-  ERR=${?};
-fi
-if [[ ${ERR} -eq 0 ]];
-then
-  echo "Available sentinels:"
-  ${REDIS_CLI} ${REDIS_SENTINEL_PASSWORD} \
-    -h ${REDIS_SENTINEL_IP} -p ${REDIS_SENTINEL_PORT} SENTINEL sentinels <%= spec.deployment %>;
-  ERR=${?};
-fi
-<% end %>
+SENTINEL_ERROR="";
+for x in ${SENTINEL_ADDRESSES};
+do
+  MSG="$(${CLI} \
+    ${SENTINEL_PASSWORD} \
+    -h ${x} \
+    -p ${SENTINEL_PORT} \
+    PING)";
+  if [[ ${?} -eq 0 ]] && [[ "${MSG}" == "PONG" ]];
+  then
+    echo "Redis Sentinel at address [${x}] and port [${SENTINEL_PORT}] is available: ${MSG}";
+    MSG="(${CLI} \
+      ${SENTINEL_PASSWORD} \
+      -h ${x} \
+      -p ${SENTINEL_PORT} \
+      SENTINEL master <%= spec.deployment %>)";
+    if [[ ${?} -eq 0 ]];
+    then
+      echo "Available master for <%= spec.deployment %> : ${MSG}";
+      MSG="(${CLI} \
+        ${SENTINEL_PASSWORD} \
+        -h ${x} \
+        -p ${SENTINEL_PORT} \
+        SENTINEL slaves <%= spec.deployment %>)";
+    else
+      echo "ERROR: Unable to find Redis master for <%= spec.deployment %> from Redis Sentinel ${x} : ${MSG}" >&2;
+    fi
+    if [[ ${?} -eq 0 ]];
+    then
+      echo "Available slaves for <%= spec.deployment %> : ${MSG}"
+      MSG="(${CLI} \
+        ${SENTINEL_PASSWORD} \
+        -h ${x} \
+        -p ${SENTINEL_PORT} \
+        SENTINEL sentinels <%= spec.deployment %>)";
+    else
+      echo "ERROR: Unable to find Redis slaves for <%= spec.deployment %> from Redis Sentinel ${x} : ${MSG}" >&2;
+    fi
+    if [[ ${?} -eq 0 ]];
+    then
+      echo "Available sentinels for <%= spec.deployment %> : ${MSG}";
+    else
+      echo "ERROR: Unable to find Redis Sentinel for <%= spec.deployment %> from Redis Sentinel ${x} : ${MSG}" >&2;
+    fi
+  else
+    echo "ERROR: Redis Sentinel at address [${x}] and port [${SENTINEL_PORT}] is unavailable: ${MSG}" >&2;
+  fi
+  if [[ ${?} -ne 0 ]];
+  then
+    ERR=1;
+    SENTINEL_ERROR+="${x} ";
+  fi
+done
+<%- end -%>
 
 #
 # Look up Redis cluster
 #
-REDIS_CLI_CLUSTER_OPTS="";
-<% if master.p('cluster_enabled').eql?('yes') %>
-REDIS_CLI_CLUSTER_OPTS="-c";
-<%
-  addresses=''
+CLUSTER_OPTS="";
+<%- if master.p('cluster_enabled').eql?('yes') -%>
+CLUSTER_OPTS="-c";
+<%- addresses=''
   master.instances.each{ |x| addresses.concat(x.address).concat(' ') }
-  instances=master.instances.length
-%>
-REDIS_MASTER_ADDRESSES="<%= addresses %>";
-REDIS_MASTER_INSTANCES="<%= instances %>";
-<%
-  slaves_addresses=''
+  instances=master.instances.length -%>
+MASTER_ADDRESSES="<%= addresses %>";
+MASTER_INSTANCES="<%= instances %>";
+<%- slaves_addresses=''
   slave_instances=0
   if !slave.instances[0].name.eql?(master.instances[0].name)
     slave.instances.each{ |x| slaves_addresses.concat(x.address).concat(' ') }
     slave_instances=slave.instances.length
   end
   addresses.concat(slaves_addresses)
-  instances+=slave_instances
-%>
-REDIS_SLAVE_ADDRESSES="<%= slaves_addresses %>";
-REDIS_SLAVE_INSTANCES="<%= slave_instances %>";
+  instances+=slave_instances -%>
+SLAVE_ADDRESSES="<%= slaves_addresses %>";
+SLAVE_INSTANCES="<%= slave_instances %>";
 REDIS_ADDRESSES="<%= addresses %>";
 REDIS_INSTANCES="<%= instances %>";
-
 SLAVE_PER_INSTANCE="<%= master.p('cluster_replicas_per_node') %>";
 
-REDIS_CLUSTER_NODES_COMMAND="$(${REDIS_CLI} ${REDIS_PASSWORD} \
-  -h ${REDIS_IP} -p ${REDIS_PORT} CLUSTER NODES)";
+CLUSTER_NODES="$(${CLI} \
+  ${REDIS_PASSWORD} \
+  -h ${REDIS_IP} \
+  -p ${REDIS_PORT} \
+  CLUSTER NODES)";
 ERR=${?};
 if [[ ${ERR} -eq 0 ]];
 then
   echo "Redis CLUSTER NODES command results:";
-  echo "${REDIS_CLUSTER_NODES_COMMAND}";
+  echo "${CLUSTER_NODES}";
   AVAILABLE_NODES=0;
-  for i in $(echo "${REDIS_CLUSTER_NODES_COMMAND}" | awk '{print $2;}');
+  for i in $(echo "${CLUSTER_NODES}" | awk '{print $2;}');
   do
     for j in ${REDIS_ADDRESSES};
     do
@@ -136,14 +157,14 @@ then
   done
   if [[ ${REDIS_INSTANCES} -eq ${AVAILABLE_NODES} ]];
   then
-    echo "All requested Redis nodes [${REDIS_INSTANCES}] are available the cluster";
-<% if !slave.instances[0].name.eql?(master.instances[0].name) %>
-    REDIS_CLUSTER_NODES_MASTER="$(echo "${REDIS_CLUSTER_NODES_COMMAND}" | \
+    echo "All requested Redis nodes [${REDIS_INSTANCES}] are available.";
+<%- if !slave.instances[0].name.eql?(master.instances[0].name) -%>
+    MASTER_NODES="$(echo "${CLUSTER_NODES}" | \
       awk '$3~/master/{print $2;}')";
     AVAILABLE_NODES=0;
-    for i in ${REDIS_MASTER_ADDRESSES};
+    for i in ${MASTER_ADDRESSES};
     do
-      for j in ${REDIS_CLUSTER_NODES_MASTER};
+      for j in ${MASTER_NODES};
       do
         if [[ "${i}:${REDIS_PORT}" == "${j%%@*}" ]];
         then
@@ -151,20 +172,20 @@ then
         fi
       done
     done
-    if [[ ${REDIS_MASTER_INSTANCES} -eq ${AVAILABLE_NODES} ]];
+    if [[ ${MASTER_INSTANCES} -eq ${AVAILABLE_NODES} ]];
     then
-      echo "All requested Redis master nodes [${REDIS_MASTER_INSTANCES}] are available";
+      echo "All requested Redis master nodes [${MASTER_INSTANCES}] are available.";
       ERR=0;
     else
-      echo "WARNING: The requested Redis master nodes [${REDIS_MASTER_INSTANCES}] is not equal to the initial available master nodes [${AVAILABLE_NODES}]" >&2;
+      echo "WARNING: The requested Redis master nodes [${MASTER_INSTANCES}] is not equal to the initial available master nodes [${AVAILABLE_NODES}]." >&2;
       ERR=1;
     fi
-    REDIS_CLUSTER_NODES_SLAVE="$(echo "${REDIS_CLUSTER_NODES_COMMAND}" | \
+    SLAVE_NODES="$(echo "${CLUSTER_NODES}" | \
       awk '$3~/slave/{print $2;}')";
     AVAILABLE_NODES=0;
-    for i in ${REDIS_SLAVE_ADDRESSES};
+    for i in ${SLAVE_ADDRESSES};
     do
-      for j in ${REDIS_CLUSTER_NODES_SLAVE};
+      for j in ${SLAVE_NODES};
       do
         if [[ "${i}:${REDIS_PORT}" == "${j%%@*}" ]];
         then
@@ -172,15 +193,15 @@ then
         fi
       done
     done
-    if [[ ${REDIS_SLAVE_INSTANCES} -eq ${AVAILABLE_NODES} ]];
+    if [[ ${SLAVE_INSTANCES} -eq ${AVAILABLE_NODES} ]];
     then
-      echo "All requested Redis slave nodes [${REDIS_SLAVE_INSTANCES}] are available";
+      echo "All requested Redis slave nodes [${SLAVE_INSTANCES}] are available.";
       ERR=0;
     else
-      echo "WARNING: The requested Redis slave nodes [${REDIS_SLAVE_INSTANCES}] is not equal to the initial available slave nodes [${AVAILABLE_NODES}]" >&2;
+      echo "WARNING: The requested Redis slave nodes [${SLAVE_INSTANCES}] is not equal to the initial available slave nodes [${AVAILABLE_NODES}]." >&2;
       ERR=1;
     fi
-<% end %>
+<%- end -%>
   else
     echo "ERROR: The requested Redis nodes [${REDIS_INSTANCES}] is not equal to the available nodes [${AVAILABLE_NODES}]" >&2;
     ERR=1;
@@ -189,7 +210,7 @@ else
   echo "ERROR: Redis CLUSTER NODES command failed." >&2;
   ERR=1;
 fi
-<% end %>
+<%- end -%>
 
 #
 # CRUD tests
@@ -197,54 +218,62 @@ fi
 if [[ ${ERR} -eq 0 ]];
 then
   KV="<%= spec.deployment+'_'+link('redis_conn').instances[spec.index].name+'_'+spec.index.to_s %>";
-  RESULT="";
-<% if master.p('replication') && !sentinel.nil? %>
-  REDIS_CLI_SENTINEL_OPTS="${REDIS_SENTINEL_PASSWORD} -h ${REDIS_SENTINEL_IP} -p ${REDIS_SENTINEL_PORT} SENTINEL";
-  REDIS_SENTINEL_MASTER="$(${REDIS_CLI} ${REDIS_CLI_SENTINEL_OPTS} get-master-addr-by-name <%= spec.deployment %>)";
-  REDIS_IP="${REDIS_SENTINEL_MASTER%%[[:space:]]*}";
-  REDIS_PORT="${REDIS_SENTINEL_MASTER#*[[:space:]]}";
-<% end %>
-  REDIS_CLI_OPTS="${REDIS_PASSWORD} ${REDIS_CLI_CLUSTER_OPTS} -h ${REDIS_IP} -p ${REDIS_PORT}";
-  ${REDIS_CLI} ${REDIS_CLI_OPTS} SET ${KV} ${KV};
-  ERR=${?};
-  if [[ ${ERR} -eq 0 ]];
-  then
-    echo "Create operation: succeed";
-    RESULT="$(${REDIS_CLI} ${REDIS_CLI_OPTS} GET ${KV})";
-    ERR=${?};
-    if [[ ${ERR} -eq 0 ]] && [[ "${KV}" == "${RESULT}" ]];
-    then
-      echo "Read operation: succeed";
-      ${REDIS_CLI} ${REDIS_CLI_OPTS} APPEND ${KV} ${KV};
-      ERR=${?};
-      if [[ ${ERR} -eq 0 ]];
-      then
-        echo "Append operation: succeed";
-        RESULT="$(${REDIS_CLI} ${REDIS_CLI_OPTS} GET ${KV})";
-        ERR=${?};
-        if [[ ${ERR} -eq 0 ]] && [[ "${KV}${KV}" == "${RESULT}" ]];
-        then
-          echo "Update operation: succeed";
-        else
-          echo "Update operation: failed";
-        fi
-      else
-        echo "Append operation: failed";
-      fi
-    else
-      echo "Read operation: failed";
-    fi
-    ${REDIS_CLI} ${REDIS_CLI_OPTS} DEL ${KV};
+<%- if master.p('replication') && !sentinel.nil? -%>
+  for x in ${SENTINEL_ADDRESSES};
+  do
+    REDIS_MASTER="$(${CLI} \
+      ${SENTINEL_PASSWORD} \
+      -h ${x} \
+      -p ${SENTINEL_PORT} \
+      SENTINEL get-master-addr-by-name <%= spec.deployment %>)";
+    REDIS_IP="${REDIS_MASTER%%[[:space:]]*}";
+    REDIS_PORT="${REDIS_MASTER#*[[:space:]]}";
+    echo "CRUD operations to Redis master [${REDIS_IP}:${REDIS_PORT}] get from Sentinel [${x}] :";
+<%- end -%>
+    CLI_OPTS="${REDIS_PASSWORD} ${CLUSTER_OPTS} -h ${REDIS_IP} -p ${REDIS_PORT}";
+    MSG="$(${CLI} ${CLI_OPTS} SET ${KV} ${KV})";
     ERR=${?};
     if [[ ${ERR} -eq 0 ]];
     then
-      echo "Delete operation: succeed";
+      echo "Create operation: succeed.";
+      MSG="$(${CLI} ${CLI_OPTS} GET ${KV})";
+      ERR=${?};
+      if [[ ${ERR} -eq 0 ]] && [[ "${KV}" == "${MSG}" ]];
+      then
+        echo "Read operation: succeed";
+        MSG="$(${CLI} ${CLI_OPTS} APPEND ${KV} ${KV})";
+        ERR=${?};
+        if [[ ${ERR} -eq 0 ]];
+        then
+          echo "Append operation: succeed";
+          MSG="$(${CLI} ${CLI_OPTS} GET ${KV})";
+          ERR=${?};
+          if [[ ${ERR} -eq 0 ]] && [[ "${KV}${KV}" == "${MSG}" ]];
+          then
+            echo "Update operation: succeed.";
+          else
+            echo "ERROR: Update operation: ${MSG}" >&2;
+          fi
+        else
+          echo "ERROR: Append operation: ${MSG}" >&2;
+        fi
+      else
+        echo "ERROR: Read operation: ${MSG}" >&2;
+      fi
+      MSG="$(${CLI} ${CLI_OPTS} DEL ${KV})";
+      ERR=${?};
+      if [[ ${ERR} -eq 0 ]];
+      then
+        echo "Delete operation: succeed.";
+      else
+        echo "ERROR: Delete operation: ${MSG}" >&2;
+      fi
     else
-      echo "Delete operation: failed";
+      echo "ERROR: Create operation: ${MSG}" >&2;
     fi
-  else
-    echo "Create operation: failed";
-  fi
+<%- if master.p('replication') && !sentinel.nil? -%>
+  done
+<%- end -%>
 fi
 
 exit ${ERR};
