1.0.3.1

diff --git a/jobs/redis/templates/bin/pre-start.erb b/jobs/redis/templates/bin/pre-start.erb
--- a/jobs/redis/templates/bin/pre-start.erb
+++ b/jobs/redis/templates/bin/pre-start.erb
@@ -1,6 +1,8 @@
 #!/bin/bash
+<%- master=link('redis_conn') -%>
+
 ERR=0;
-<%- if link('redis_conn').p('tls') -%>
+<%- if master.p('tls') -%>
 source "/var/vcap/packages/redis/bin/gen-certs.sh";
 TLS_KEYS_DIR="<%= p('tls_keys_dir') %>";
 gen_signed_cert \
@@ -19,5 +21,24 @@ gen_dh \
 chown -R vcap:vcap "${TLS_KEYS_DIR}" && \
 chmod -R g-rwx,o-rwx "${TLS_KEYS_DIR}";
 ERR=${?};
+<%- end
+  if master.p('cluster_enabled').eql?('yes') -%>
+RUN_DIR="<%= p('run_dir') %>";
+STORE_DIR="<%= p('store_dir') %>";
+<%- node_port=master.p('port')
+  if master.p('tls') && master.p('tls_cluster')
+    node_port=master.p('tls_port')
+  end -%>
+CONF_FILE_NAME="<%= 'nodes-'+node_port.to_s+'.conf' %>";
+if [[ -f "${STORE_DIR}/config/${CONF_FILE_NAME}" ]];
+then
+  if [[ $(cp -f "${STORE_DIR}/config/${CONF_FILE_NAME}" "${RUN_DIR}/.") -ne 0 ]];
+  then
+    ERR=1;
+    echo "ERROR: Unable to copy ${STORE_DIR}/config/${CONF_FILE_NAME} to ${RUN_DIR}/." >&2;
+  else
+    echo "Redis Sentinel backup file ${STORE_DIR}/config/${CONF_FILE_NAME} restored in ${RUN_DIR}/.";
+  fi
+fi
 <%- end -%>
 exit ${ERR};
diff --git a/jobs/redis/templates/bin/pre-stop.erb b/jobs/redis/templates/bin/pre-stop.erb
--- a/jobs/redis/templates/bin/pre-stop.erb
+++ b/jobs/redis/templates/bin/pre-stop.erb
@@ -1,41 +1,41 @@
 #!/bin/bash
-<%- sentinel=nil
+<%- master=link('redis_conn')
+  sentinel=nil
   if_link('redis_sentinel_conn'){ |x| sentinel=x }
   sentinel_slave=nil
   if_link('sentinel_slave_conn'){ |x| sentinel_slave=x } -%>
 
 ERR=0;
-
+CLI="/var/vcap/packages/redis/bin/redis-cli";
 <%- if !sentinel.nil? -%>
+PORT="<%= sentinel.p('port') %>";
+CRED="";
+<%- sentinel.if_p('password') do |x|
+    unless x.to_s.empty? -%>
+CRED="-a <%= x %>";
+<%- end
+  end
+  if sentinel.p('tls') -%>
+PORT="<%= sentinel.p('tls_port') %>";
+TLS_KEYS_DIR="<%= p('tls_keys_dir') %>";
+CRED+=" --tls --cert ${TLS_KEYS_DIR}/<%= p('tls_cert_file') %>";
+CRED+=" --key ${TLS_KEYS_DIR}/<%= p('tls_key_file') %>";
+CRED+=" --cacert ${TLS_KEYS_DIR}/<%= p('tls_ca_cert_file') %>";
+<%- end
+  sentinel_addresses=''
+  sentinel.instances.each{ |x| sentinel_addresses.concat(x.address).concat(' ') }
+  if !sentinel_slave.nil?
+    sentinel_slave.instances.each{ |x| sentinel_addresses.concat(x.address).concat(' ') }
+  end -%>
+SENTINEL_ADDRESSES="<%= sentinel_addresses %>";
 if [[ ${BOSH_DEPLOYMENT_NEXT_STATE} == "delete" ]];
 then
-  CLI="/var/vcap/packages/redis/bin/redis-cli";
-  SENTINEL_PORT="<%= sentinel.p('port') %>";
-  SENTINEL_CRED="";
-  <%- sentinel.if_p('password') do |x|
-      unless x.to_s.empty? -%>
-  SENTINEL_CRED="-a <%= x %>";
-  <%- end
-    end 
-    if sentinel.p('tls') -%>
-  SENTINEL_PORT="<%= sentinel.p('tls_port') %>";
-  SENTINEL_CRED+=" --tls --cert ${TLS_CERT_FILE}";
-  SENTINEL_CRED+=" --key ${TLS_KEY_FILE}";
-  SENTINEL_CRED+=" --cacert ${TLS_CA_CERT_FILE}";
-  <%- end
-    sentinel_addresses=''
-    sentinel.instances.each{ |x| sentinel_addresses.concat(x.address).concat(' ') }
-    if !sentinel_slave.nil?
-      sentinel_slave.instances.each{ |x| sentinel_addresses.concat(x.address).concat(' ') }
-    end -%>
-  SENTINEL_ADDRESSES="<%= sentinel_addresses %>";
-
   for x in ${SENTINEL_ADDRESSES};
   do
     MSG="$("${CLI}" \
       -h "${x}" \
-      -p "${SENTINEL_PORT}" \
-      ${SENTINEL_CRED} \
+      -p "${PORT}" \
+      ${CRED} \
       SENTINEL REMOVE <%= spec.deployment %>)";
     if [[ ${?} -eq 0 ]];
     then
@@ -45,6 +45,54 @@ then
       echo "ERROR: Unable to removed [<%= spec.deployment %>] from Sentinel [${x}]: \"${MSG}\"." >&2;
     fi
   done
+fi
+<%- end
+  if master.p('cluster_enabled').eql?('yes') -%>
+IP="127.0.0.1";
+<%- if master.p('bind') -%>
+IP="<%= spec.ip %>";
+<%- end -%>
+PORT="<%= master.p('port') %>";
+CRED="--user <%= master.p('admin_user') %>";
+<%- master.if_p('admin_password') do |x|
+    unless x.to_s.empty? -%>
+CRED+=" --pass <%= x %>";
+<%- end
+  end
+  if master.p('tls') -%>
+PORT="<%= master.p('tls_port') %>";
+TLS_KEYS_DIR="<%= p('tls_keys_dir') %>";
+CRED+=" --tls --cert ${TLS_KEYS_DIR}/<%= p('tls_cert_file') %>";
+CRED+=" --key ${TLS_KEYS_DIR}/<%= p('tls_key_file') %>";
+CRED+=" --cacert ${TLS_KEYS_DIR}/<%= p('tls_ca_cert_file') %>";
+<%- end -%>
+RUN_DIR="<%= p('run_dir') %>";
+STORE_DIR="<%= p('store_dir') %>";
+<%- node_port=master.p('port')
+  if master.p('tls') && master.p('tls_cluster')
+    node_port=master.p('tls_port')
+  end -%>
+CONF_FILE_NAME="<%= 'nodes-'+node_port.to_s+'.conf' %>";
+if [[ "${BOSH_DEPLOYMENT_NEXT_STATE}" == "delete" ]];
+then
+  rm -f "${STORE_DIR}/config/${CONF_FILE_NAME}";
+else
+  MSG="$("${CLI}" \
+    -h "${IP}" \
+    -p "${PORT}" \
+    ${CRED} \
+    CLUSTER SAVECONFIG)";
+  if [[ ${?} -eq 0 ]];
+  then
+    if [[ $(mkdir -p "${STORE_DIR}/config") -ne 0 ]] || \
+      [[ $(cp -f "${RUN_DIR}/${CONF_FILE_NAME}" "${STORE_DIR}/config/.") -ne 0 ]];
+    then
+      ERR=1;
+      echo "ERROR: Unable to copy ${RUN_DIR}/${CONF_FILE_NAME} to ${STORE_DIR}/config/." >&2;
+    else
+      echo "Redis cluster nodes configuration ${RUN_DIR}/${CONF_FILE_NAME} is backuped in ${STORE_DIR}/config/.";
+    fi
+  fi
 fi
 <%- end -%>
 
diff --git a/jobs/redis_sentinel/templates/bin/pre-stop.erb b/jobs/redis_sentinel/templates/bin/pre-stop.erb
--- a/jobs/redis_sentinel/templates/bin/pre-stop.erb
+++ b/jobs/redis_sentinel/templates/bin/pre-stop.erb
@@ -1,13 +1,8 @@
 #!/bin/bash
 <%- sentinel=link('redis_sentinel_conn') -%>
 
+ERR=0
 CLI="/var/vcap/packages/redis/bin/redis-cli";
-LOG_DIR="<%= p('log_dir') %>";
-LOG_FILE="${LOG_DIR}/<%= p('logfile') %>";
-STORE_DIR="<%= p('dir') %>";
-CONF_DIR="/var/vcap/jobs/redis_sentinel/config";
-CONF_FILE_NAME="redis_sentinel.conf";
-CONF_FILE="${CONF_DIR}/${CONF_FILE_NAME}";
 IP="127.0.0.1";
 <%- if sentinel.p('bind') -%>
 IP="<%= spec.ip %>";
@@ -26,8 +21,9 @@ CRED+=" --tls --cert ${TLS_KEYS_DIR}/<%= p('tls_cert_file') %>";
 CRED+=" --key ${TLS_KEYS_DIR}/<%= p('tls_key_file') %>";
 CRED+=" --cacert ${TLS_KEYS_DIR}/<%= p('tls_ca_cert_file') %>";
 <%- end -%>
-
-ERR=0
+STORE_DIR="<%= p('store_dir') %>";
+CONF_DIR="/var/vcap/jobs/redis_sentinel/config";
+CONF_FILE_NAME="redis_sentinel.conf";
 if [[ "${BOSH_DEPLOYMENT_NEXT_STATE}" == "delete" ]];
 then
   rm -f "${STORE_DIR}/config/${CONF_FILE_NAME}";
@@ -40,14 +36,13 @@ else
   if [[ ${?} -eq 0 ]];
   then
     if [[ $(mkdir -p "${STORE_DIR}/config") -ne 0 ]] || \
-      [[ $(cp -f "${CONF_FILE}" "${STORE_DIR}/config/.") -ne 0 ]];
+      [[ $(cp -f "${CONF_DIR}/${CONF_FILE_NAME}" "${STORE_DIR}/config/.") -ne 0 ]];
     then
       ERR=1;
-      echo "ERROR: Unable to copy ${CONF_FILE} to ${STORE_DIR}/config/." >&2;
+      echo "ERROR: Unable to copy ${CONF_DIR}/${CONF_FILE_NAME} to ${STORE_DIR}/config/." >&2;
     else
-      echo "Redis Sentinel configuration ${CONF_FILE} is backuped in ${STORE_DIR}/config/.";
+      echo "Redis Sentinel configuration ${CONF_DIR}/${CONF_FILE_NAME} is backuped in ${STORE_DIR}/config/.";
     fi
   fi
 fi
-
 exit ${ERR};
